### PR TITLE
Add code of conduct for contributing 

### PR DESCRIPTION
**Pull request by prahaladbelavadi**

### CODE REVIEW

**Comment by izqui** [comment]
Please link to Aragon's Community Code of Conduct too https://wiki.aragon.one/documentation/Code_of_Conduct/

@onbjerg why does this PR affect coverage so much?

**Comment by onbjerg** [comment]
I actually have no clue. I'll investigate.

Anyway, can you please rename it to `CODE_OF_CONDUCT.md` and put it in the `.github` folder? This ensures we don't clutter the root of the project.

**Comment by prahaladbelavadi** [comment]
Done @izqui 
made another pull request [here](https://github.com/aragon/node-aragon/pull/10)

**Comment by onbjerg** [comment]
Closed in favor of #10

**Pull request closed without merging**
